In [ ]:
import cv as cv
import matplotlib.pyplot as plt
import os
import time
import mediapipe as mp
import numpy as np

2025-07-23 10:45:16.164213: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-23 10:45:16.287346: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1753247716.332538    4507 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1753247716.345902    4507 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1753247716.455847    4507 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
mp_face_mesh = mp.solutions.face_mesh 

In [3]:
def mediapipe_detection(image, model):
    image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = model.process(image)
    image.flags.writeable = True
    image = cv.cvtColor(image, cv.COLOR_RGB2BGR)
    return image, results

In [4]:
def draw_landmarks(image, result):
    if result.face_landmarks:
        mp_drawing.draw_landmarks(image, result.face_landmarks, mp_face_mesh.FACEMESH_TESSELATION)
    if result.pose_landmarks:
        mp_drawing.draw_landmarks(image, result.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
    if result.left_hand_landmarks:
        mp_drawing.draw_landmarks(image, result.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
    if result.right_hand_landmarks:
        mp_drawing.draw_landmarks(image, result.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)


In [5]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 


In [6]:
cap = cv.VideoCapture('sign.mp4')
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        ret, frame = cap.read()
        if not ret:
            print("Video ended or cannot read the frame.")
            break

        image, results = mediapipe_detection(frame, holistic)
            

        draw_styled_landmarks(image, results)

        cv.imshow('OpenCV feed', image)
        if cv.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv.destroyAllWindows()

I0000 00:00:1753247718.441606    4507 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1753247718.507087    7024 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 570.172.08), renderer: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1753247718.551707    7000 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753247718.571255    7001 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753247718.573411    7002 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753247718.573514    6997 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature 

In [7]:
results.right_hand_landmarks

In [8]:
frame

array([[[132, 130, 134],
        [128, 126, 130],
        [133, 131, 135],
        ...,
        [114, 118, 125],
        [114, 118, 125],
        [114, 118, 125]],

       [[130, 128, 132],
        [130, 128, 132],
        [135, 133, 137],
        ...,
        [114, 118, 125],
        [114, 118, 125],
        [114, 118, 125]],

       [[129, 127, 131],
        [133, 131, 135],
        [136, 134, 138],
        ...,
        [114, 118, 125],
        [114, 118, 125],
        [114, 118, 125]],

       ...,

       [[164, 164, 158],
        [162, 162, 156],
        [162, 162, 156],
        ...,
        [ 83,  96, 116],
        [ 84,  97, 116],
        [ 83,  96, 115]],

       [[157, 157, 151],
        [158, 158, 152],
        [162, 162, 156],
        ...,
        [ 83,  96, 116],
        [ 83,  96, 115],
        [ 82,  95, 114]],

       [[150, 150, 144],
        [153, 153, 147],
        [158, 158, 152],
        ...,
        [ 83,  96, 116],
        [ 83,  96, 115],
        [ 81,  94, 113]]

## Extracting Keypoint Values

In [9]:
results.pose_landmarks.landmark[0]

x: 0.267064571
y: 0.373800635
z: -1.2376591
visibility: 0.999559462

In [10]:
results.pose_landmarks.landmark[0].x

0.26706457138061523

In [11]:
results.pose_landmarks.landmark[0].y

0.3738006353378296

In [12]:
results.pose_landmarks.landmark[0].z

-1.2376590967178345

In [13]:
pose = []

for res in results.pose_landmarks.landmark:
   test = np.array([res.x, res.y, res.z, res.visibility])
   pose.append(test)

In [14]:
pose

[array([ 0.26706457,  0.37380064, -1.2376591 ,  0.99955946]),
 array([ 0.32199806,  0.33850104, -1.26252556,  0.99942458]),
 array([ 0.34669897,  0.33909333, -1.26285565,  0.99947667]),
 array([ 0.37435278,  0.34005755, -1.26354063,  0.99954122]),
 array([ 0.27456048,  0.34040743, -1.12301517,  0.99911761]),
 array([ 0.26380023,  0.34214309, -1.12236619,  0.99908227]),
 array([ 0.25443962,  0.34368473, -1.12325418,  0.99896157]),
 array([ 0.47343865,  0.36998665, -1.05041969,  0.9996441 ]),
 array([ 0.31070083,  0.36960784, -0.45877403,  0.99903291]),
 array([ 0.31194615,  0.41558728, -1.17136073,  0.99979192]),
 array([ 0.25505346,  0.41499743, -0.98817545,  0.99955064]),
 array([ 0.76034522,  0.62633032, -0.89239115,  0.99897307]),
 array([ 0.14385974,  0.60643607, -0.12092006,  0.99661833]),
 array([ 0.89377958,  0.91359901, -0.99031186,  0.58975136]),
 array([-0.00503417,  0.85288489, -0.08946221,  0.24279097]),
 array([ 1.01304817,  1.17175007, -1.33636642,  0.10235522]),
 array([

In [15]:
pose = np.array(pose)

In [16]:
pose.shape

(33, 4)

In [17]:
pose.flatten().shape

(132,)

In [18]:
pose = pose.flatten()

In [19]:
pose.shape

(132,)

In [20]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [21]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [22]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, face, lh, rh])

In [23]:
extract_keypoints(results).shape

(1662,)

In [24]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['hello', 'thanks', 'iloveyou'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30



In [25]:
DATA_PATH = 'MP_Data'

# Automatically gather class labels from folder names
actions = np.array(sorted([folder for folder in os.listdir(DATA_PATH) if os.path.isdir(os.path.join(DATA_PATH, folder))]))
print("Detected actions:", actions)

Detected actions: ['bye' 'copy' 'disgust' 'eternity' 'hello' 'human' 'love' 'thanks']


In [26]:
# with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
#     for action in actions:
#         action_path = os.path.join(DATA_PATH, action)
#         video_files = [f for f in os.listdir(action_path) if f.endswith('.mp4')]

#         for sequence, video_file in enumerate(video_files):
#             cap = cv.VideoCapture(os.path.join(action_path, video_file))
#             frame_num = 0

#             while cap.isOpened() and frame_num < sequence_length:
#                 ret, frame = cap.read()
#                 if not ret:
#                     break

#                 _, results = mediapipe_detection(frame, holistic)
#                 keypoints = extract_keypoints(results)

#                 # Save keypoints as .npy
#                 sequence_dir = os.path.join(DATA_PATH, action, str(sequence))
#                 os.makedirs(sequence_dir, exist_ok=True)
#                 npy_path = os.path.join(sequence_dir, f'{frame_num}.npy')
#                 np.save(npy_path, keypoints)

#                 frame_num += 1
#             cap.release()

In [27]:
label_map = {label: num for num, label in enumerate(actions)}

In [28]:
label_map

{'bye': 0,
 'copy': 1,
 'disgust': 2,
 'eternity': 3,
 'hello': 4,
 'human': 5,
 'love': 6,
 'thanks': 7}

In [29]:
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

In [30]:
sequences, labels = [], []
for action in actions:
    for sequence in range(4):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])


In [31]:
np.array(sequences).shape

(32, 30, 1662)

In [32]:
X = np.array(sequences)

In [33]:
y = to_categorical(labels).astype(int)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, RNN, Bidirectional, Dense, Dropout
from tensorflow.keras.callbacks import TensorBoard

In [36]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [37]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))


I0000 00:00:1753247720.490810    4507 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9116 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9
/home/smayan/Desktop/AI-ML-DS/AI-and-ML-Course/.conda/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [38]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 596,840 (2.28 MB)

 Trainable params: 596,840 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

In [41]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 596,840 (2.28 MB)

 Trainable params: 596,840 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.save('action2.h5')

In [43]:
model.save('action2.keras')

In [48]:
import tensorflow as tf
model = tf.keras.models.load_model('action.h5')

In [49]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 30, 128)        │       884,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 927,786 (3.54 MB)

 Trainable params: 927,784 (3.54 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [50]:
model.load_weights('action.h5')

In [51]:
res = model.predict(X_test)

I0000 00:00:1753248187.517251    7116 service.cc:152] XLA service 0x7f82b0001cc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1753248187.517268    7116 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 SUPER, Compute Capability 8.9
2025-07-23 10:53:07.545343: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1753248187.658708    7116 cuda_dnn.cc:529] Loaded cuDNN version 91100


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 637ms/step


I0000 00:00:1753248187.958054    7116 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


In [52]:
res

array([[1.9059086e-02, 1.3626700e-02, 2.5284049e-01, 2.5411421e-01,
        8.2307644e-02, 2.7819473e-01, 2.2096965e-02, 7.7760160e-02],
       [1.0660870e-10, 1.3511191e-01, 7.5052892e-05, 5.2560239e-08,
        2.6089751e-06, 1.8602709e-01, 6.7878276e-01, 4.5567529e-07],
       [8.8261318e-01, 6.0613627e-05, 1.0983580e-01, 5.2947975e-03,
        1.0672770e-07, 4.7394878e-06, 3.1562660e-05, 2.1591443e-03],
       [1.5745857e-01, 4.8438224e-04, 5.2396744e-01, 2.5058228e-01,
        6.6656474e-04, 3.2238713e-03, 2.0909614e-03, 6.1525945e-02]],
      dtype=float32)

In [53]:
res[0]

array([0.01905909, 0.0136267 , 0.2528405 , 0.2541142 , 0.08230764,
       0.27819473, 0.02209697, 0.07776016], dtype=float32)

In [54]:
np.sum(res[0])

0.9999999

In [55]:
np.argmax(res[0])

5

In [68]:
actions[np.argmax(res[3])]

'disgust'

In [69]:
actions[np.argmax(y_test[3])]

'disgust'

In [70]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [71]:
yhat = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


In [ ]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [73]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[3, 0],
        [0, 1]],

       [[3, 0],
        [0, 1]],

       [[3, 1],
        [0, 0]],

       [[3, 0],
        [0, 1]],

       [[3, 0],
        [1, 0]]])

In [74]:
accuracy_score(ytrue, yhat)

0.75

In [ ]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv.putText(output_frame, actions[num], (0, 85+num*40), cv.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv.LINE_AA)
        
    return output_frame

In [76]:
plt.figure(figsize=(18,18))
plt.imshow(prob_viz(res, actions, image, colors))

TypeError: only length-1 arrays can be converted to Python scalars

<Figure size 1800x1800 with 0 Axes>

In [78]:
# 1. New detection variables
sequence = []
sentence = []
threshold = 0.8

cap = cv.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv.putText(image, ' '.join(sentence), (3,30), 
                       cv.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv.destroyAllWindows()

[ WARN:0@1674.971] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1674.972] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
I0000 00:00:1753249390.487355    4507 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1753249390.528703   15628 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 570.172.08), renderer: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
W0000 00:00:1753249390.563184   15604 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753249390.581075   15617 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753249390.582339   15617 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling suppor