In [1]:
import cv2 as cv
import matplotlib.pyplot as plt
import os
import time
import mediapipe as mp
import numpy as np

2025-07-22 12:01:16.045825: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-22 12:01:16.052823: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1753165876.060845   38509 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1753165876.063209   38509 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1753165876.069652   38509 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
mp_face_mesh = mp.solutions.face_mesh 

In [3]:
def mediapipe_detection(image, model):
    image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = model.process(image)
    image.flags.writeable = True
    image = cv.cvtColor(image, cv.COLOR_RGB2BGR)
    return image, results

In [4]:
def draw_landmarks(image, result):
    if result.face_landmarks:
        mp_drawing.draw_landmarks(image, result.face_landmarks, mp_face_mesh.FACEMESH_TESSELATION)
    if result.pose_landmarks:
        mp_drawing.draw_landmarks(image, result.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
    if result.left_hand_landmarks:
        mp_drawing.draw_landmarks(image, result.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
    if result.right_hand_landmarks:
        mp_drawing.draw_landmarks(image, result.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)


In [5]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 


In [6]:
cap = cv.VideoCapture('sign.mp4')
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        ret, frame = cap.read()
        if not ret:
            print("Video ended or cannot read the frame.")
            break

        image, results = mediapipe_detection(frame, holistic)
            

        draw_styled_landmarks(image, results)

        cv.imshow('OpenCV feed', image)
        if cv.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv.destroyAllWindows()

I0000 00:00:1753165877.249412   38509 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1753165877.303793   38670 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 570.172.08), renderer: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1753165877.347326   38648 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753165877.366504   38661 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753165877.367830   38657 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1753165877.368154   38649 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature 

In [7]:
results.right_hand_landmarks

landmark {
  x: 0.256533235
  y: 0.70953685
  z: 6.1149143e-07
}
landmark {
  x: 0.353166759
  y: 0.685458243
  z: -0.0318341628
}
landmark {
  x: 0.430409938
  y: 0.642841339
  z: -0.0508103371
}
landmark {
  x: 0.49024272
  y: 0.607919931
  z: -0.0700347424
}
landmark {
  x: 0.54733479
  y: 0.5826419
  z: -0.0903592408
}
landmark {
  x: 0.387684345
  y: 0.571287632
  z: -0.0354279764
}
landmark {
  x: 0.426449358
  y: 0.516234934
  z: -0.0712709203
}
landmark {
  x: 0.455417901
  y: 0.484330714
  z: -0.0997388959
}
landmark {
  x: 0.482939392
  y: 0.455602586
  z: -0.120343491
}
landmark {
  x: 0.332180023
  y: 0.565807581
  z: -0.0461979397
}
landmark {
  x: 0.349985749
  y: 0.503680646
  z: -0.077938579
}
landmark {
  x: 0.367573202
  y: 0.463561684
  z: -0.104631148
}
landmark {
  x: 0.383065253
  y: 0.427506626
  z: -0.124611169
}
landmark {
  x: 0.276951462
  y: 0.574835956
  z: -0.0617514029
}
landmark {
  x: 0.282760978
  y: 0.516595244
  z: -0.0931826
}
landmark {
  x: 0.2958

In [8]:
frame

array([[[120, 119, 121],
        [123, 122, 124],
        [128, 128, 128],
        ...,
        [108, 112, 118],
        [108, 112, 118],
        [108, 112, 118]],

       [[121, 120, 122],
        [123, 122, 124],
        [127, 127, 127],
        ...,
        [108, 112, 118],
        [108, 112, 118],
        [108, 112, 118]],

       [[122, 121, 123],
        [124, 123, 125],
        [126, 126, 126],
        ...,
        [108, 112, 118],
        [108, 112, 118],
        [108, 112, 118]],

       ...,

       [[170, 163, 157],
        [168, 161, 155],
        [165, 158, 152],
        ...,
        [118, 124, 131],
        [109, 115, 122],
        [108, 114, 121]],

       [[163, 156, 150],
        [166, 159, 153],
        [164, 157, 151],
        ...,
        [114, 120, 127],
        [113, 119, 126],
        [115, 121, 128]],

       [[161, 154, 148],
        [164, 157, 151],
        [164, 157, 151],
        ...,
        [112, 118, 125],
        [112, 118, 125],
        [117, 123, 130]]

## Extracting Keypoint Values

In [9]:
results.pose_landmarks.landmark[0]

x: 0.443604648
y: 0.405036062
z: -1.70512319
visibility: 0.999950647

In [10]:
results.pose_landmarks.landmark[0].x

0.44360464811325073

In [11]:
results.pose_landmarks.landmark[0].y

0.405036062002182

In [12]:
results.pose_landmarks.landmark[0].z

-1.7051231861114502

In [13]:
pose = []

for res in results.pose_landmarks.landmark:
   test = np.array([res.x, res.y, res.z, res.visibility])
   pose.append(test)

In [14]:
pose

[array([ 0.44360465,  0.40503606, -1.70512319,  0.99995065]),
 array([ 0.4916198 ,  0.36184865, -1.62612081,  0.99968797]),
 array([ 0.51682085,  0.36446691, -1.62521958,  0.99985874]),
 array([ 0.53996491,  0.36780903, -1.62393665,  0.99968857]),
 array([ 0.41408971,  0.35786918, -1.61921358,  0.99963903]),
 array([ 0.38804871,  0.35697639, -1.61968267,  0.99983495]),
 array([ 0.36354387,  0.35660827, -1.61964369,  0.99963623]),
 array([ 0.57840633,  0.38950568, -1.01036763,  0.99989575]),
 array([ 0.32941151,  0.37098897, -0.97443694,  0.99986911]),
 array([ 0.49845123,  0.44502193, -1.46361184,  0.99992996]),
 array([ 0.39398035,  0.4385457 , -1.45425415,  0.999897  ]),
 array([ 0.73708427,  0.59245306, -0.59905255,  0.99997824]),
 array([ 0.10981645,  0.59037763, -0.65929288,  0.9999482 ]),
 array([ 0.99783748,  0.92233211, -1.52168918,  0.99000871]),
 array([-0.0926021 ,  0.92772454, -1.45175803,  0.98049873]),
 array([ 0.77822018,  0.64977652, -2.89773989,  0.99986559]),
 array([

In [15]:
pose = np.array(pose)

In [16]:
pose.shape

(33, 4)

In [17]:
pose.flatten().shape

(132,)

In [18]:
pose = pose.flatten()

In [19]:
pose.shape

(132,)

In [20]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [21]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [22]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, face, lh, rh])

In [23]:
extract_keypoints(results).shape

(1662,)

In [24]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['hello', 'thanks', 'iloveyou'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30



In [25]:
DATA_PATH = 'MP_Data'

# Automatically gather class labels from folder names
actions = np.array(sorted([folder for folder in os.listdir(DATA_PATH) if os.path.isdir(os.path.join(DATA_PATH, folder))]))
print("Detected actions:", actions)

Detected actions: ['bye' 'copy' 'disgust' 'eternity' 'hello' 'human' 'love' 'thanks']


In [26]:
# with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
#     for action in actions:
#         action_path = os.path.join(DATA_PATH, action)
#         video_files = [f for f in os.listdir(action_path) if f.endswith('.mp4')]

#         for sequence, video_file in enumerate(video_files):
#             cap = cv.VideoCapture(os.path.join(action_path, video_file))
#             frame_num = 0

#             while cap.isOpened() and frame_num < sequence_length:
#                 ret, frame = cap.read()
#                 if not ret:
#                     break

#                 _, results = mediapipe_detection(frame, holistic)
#                 keypoints = extract_keypoints(results)

#                 # Save keypoints as .npy
#                 sequence_dir = os.path.join(DATA_PATH, action, str(sequence))
#                 os.makedirs(sequence_dir, exist_ok=True)
#                 npy_path = os.path.join(sequence_dir, f'{frame_num}.npy')
#                 np.save(npy_path, keypoints)

#                 frame_num += 1
#             cap.release()

In [27]:
label_map = {label: num for num, label in enumerate(actions)}

In [28]:
label_map

{'bye': 0,
 'copy': 1,
 'disgust': 2,
 'eternity': 3,
 'hello': 4,
 'human': 5,
 'love': 6,
 'thanks': 7}

In [29]:
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

In [30]:
sequences, labels = [], []
for action in actions:
    for sequence in range(4):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])


In [31]:
np.array(sequences).shape

(32, 30, 1662)

In [32]:
X = np.array(sequences)

In [33]:
y = to_categorical(labels).astype(int)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, RNN, Bidirectional, Dense, Dropout
from tensorflow.keras.callbacks import TensorBoard

In [36]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [37]:
model = Sequential()
model.add(Bidirectional(LSTM(64, activation='relu',return_sequences = True, ), input_shape=(30, 1662)))  # Only 1 layer
model.add(Bidirectional(LSTM(32, return_sequences=False, activation='relu')))
model.add(Dropout(0.4))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

I0000 00:00:1753165887.127122   38509 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9197 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9
/home/smayan/Desktop/AI-ML-DS/AI-and-ML-Course/.conda/lib/python3.11/site-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [38]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 30, 128)        │       884,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 927,784 (3.54 MB)

 Trainable params: 927,784 (3.54 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.fit(X_train, y_train, epochs=2000, callbacks=[tb_callback])

Epoch 1/2000


I0000 00:00:1753165943.387507   38806 service.cc:152] XLA service 0x5ca950bae850 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1753165943.387520   38806 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 SUPER, Compute Capability 8.9
2025-07-22 12:02:23.446705: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1753165943.809312   38806 cuda_dnn.cc:529] Loaded cuDNN version 91100
2025-07-22 12:02:24.459293: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_123', 20 bytes spill stores, 20 bytes spill loads



1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - categorical_accuracy: 0.1429 - loss: 2.1820
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.1071 - loss: 6.0203
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - categorical_accuracy: 0.0357 - loss: 11.6848
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - categorical_accuracy: 0.1786 - loss: 5.1235

I0000 00:00:1753165945.389109   38806 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.1786 - loss: 5.1235
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.1071 - loss: 34.1813
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - categorical_accuracy: 0.1786 - loss: 18.8140
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - categorical_accuracy: 0.1071 - loss: 11.1277
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.1429 - loss: 22.6985
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.1071 - loss: 19.5100
Epoch 10/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - categorical_accuracy: 0.1429 - loss: 5.9904
Epoch 11/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - categorical_accuracy: 0.0357 - loss: 12.2645
Epoch 12/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - categorical_accuracy: 0.2143 - loss: 17.2808
Epoch 13/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.0714 - loss: 26.0601
Epoch 14/2000
1/1 ━━━━━━━━━━━━━

In [41]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 30, 128)        │       884,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,783,354 (10.62 MB)

 Trainable params: 927,784 (3.54 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,855,570 (7.08 MB)

In [43]:
model.save('action.h5')

In [44]:
model.save('action.keras')