## Math

In [2]:
import tensorflow as tf

In [ ]:
tf1 =  tf.random.Generator.from_seed(42)

In [ ]:
tf1.normal(shape=(2, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ]], dtype=float32)>

In [22]:
com = tf.constant([32.34 + 54j])
tf.abs(com)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([62.94343175])>